version 6.0
if &cp | set nocp | endif
let s:cpo_save=&cpo
set cpo&vim
nmap gx <Plug>NetrwBrowseX
nnoremap <silent> <Plug>NetrwBrowseX :call netrw#NetBrowseX(expand("<cWORD>"),0)
let &cpo=s:cpo_save
unlet s:cpo_save
set autoindent
set backspace=indent,eol,start
set cscopeprg=/usr/bin/cscope
set cscopetag
set cscopeverbose
set fileencodings=utf-8,latin1
set formatoptions=tcql
set helplang=en
set history=50
set hlsearch
set ignorecase
set incsearch
set mouse=a
set ruler
set shiftwidth=4
set showmatch
set tabstop=4
set termencoding=utf-8
set viminfo='20,\"50
set window=35
set guifont=courier\ Bold\ 12
" some colors:  "white on black"
"hi normal   ctermfg=white  ctermbg=black guifg=DeepPink4 guibg=white
"hi normal   ctermfg=white  ctermbg=black guifg=thistle4 guibg=white
"hi normal   ctermfg=white  ctermbg=black guifg=DarkMagenta guibg=white 
hi normal   ctermfg=white  ctermbg=black guifg=OrangeRed guibg=white
"hi normal   ctermfg=black  ctermbg=black guifg=white guibg=black
"hi normal   ctermfg=white  ctermbg=black guifg=black guibg=white
hi normal   ctermfg=white  ctermbg=black guifg=DeepSkyBlue4 guibg=white
"hi nontext  ctermfg=blue   ctermbg=black guifg=blue   guibg=black
colorscheme peachpuff
syntax on
" vim: set ft=vim :
"echo "keycode 14 = BackSpace" | loadkeys
au BufNewFile,BufRead *.sv			setf verilog

syn keyword verilogStatement   class endclass
HiLink verilogStatement	 Statement

"/usr/share/vim/vim70/doc/change.txt.gz
